[package]
name = "rustwall"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
currency = "0.4.0"
html_editor = "0.7.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
thiserror = "2.0.12"
