name: Build and Deploy Rust Docs

on:
  push:
    branches:
      - master 
    paths: 
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust-docs.yml' 
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always 
      RUSTFLAGS: "-D warnings" 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy 

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build documentation
        run: cargo doc --no-deps --all-features

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Add meta
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=rustwall\">" > target/doc/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/doc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
